ReturnException: If Location contains a Return, Filemanager will throw ReturnException. WIP: still need to edit Client Class and generate correct response